project_id = "qnrqwapbxnplypdirdiq"

[functions.google-maps-proxy]
enabled = true
verify_jwt = false

[functions.send-report-email]
enabled = true
verify_jwt = false

[functions.chatbot]
enabled = true
verify_jwt = false

[functions.oauth-token-exchange]
enabled = true
verify_jwt = false
