project_id = "qnrqwapbxnplypdirdiq"

[functions.send-email]
enabled = true
verify_jwt = false

[functions.google-maps-proxy]
enabled = true
verify_jwt = false

[functions.send-report-email]
enabled = true
verify_jwt = false
