project_id = "qnrqwapbxnplypdirdiq"

[functions.send-report-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-report-email/deno.json"
entrypoint = "./functions/send-report-email/index.ts"
