export const COLOR_PALETTES = [
  {
    id: "classic-blue",
    name: "Classic Blue",
    primary: "#1e3a8a",
    secondary: "#3b82f6",
    accent: "#fcd34d",
    text: "#1f2937",
  },
  {
    id: "sunset",
    name: "Sunset",
    primary: "#f97316",
    secondary: "#fb923c",
    accent: "#f43f5e",
    text: "#1c1917",
  },
  {
    id: "forest",
    name: "Forest",
    primary: "#166534",
    secondary: "#22c55e",
    accent: "#d9f99d",
    text: "#1f2937",
  },
  {
    id: "monochrome",
    name: "Monochrome",
    primary: "#0f172a",
    secondary: "#334155",
    accent: "#64748b",
    text: "#f1f5f9",
  },
  {
    id: "lavender",
    name: "Lavender",
    primary: "#7c3aed",
    secondary: "#c4b5fd",
    accent: "#f9a8d4",
    text: "#1f2937",
  },
  {
    id: "ruby",
    name: "Ruby",
    primary: "#be123c",
    secondary: "#fda4af",
    accent: "#f87171",
    text: "#fafafa",
  },
] as const;
