export const COVER_PAGE_TEMPLATES = [
  {
    id: "centered",
    json: JSON.stringify({
      version: "5.2.1",
      objects: [
        {
          type: "text",
          originX: "center",
          originY: "top",
          left: 400,
          top: 200,
          text: "{{title}}",
          fontSize: 48,
          fontWeight: 700,
          textAlign: "center",
        },
        {
          type: "text",
          originX: "center",
          originY: "top",
          left: 400,
          top: 260,
          text: "{{subtitle}}",
          fontSize: 24,
          textAlign: "center",
        },
        {
          type: "text",
          originX: "center",
          originY: "bottom",
          left: 400,
          top: 560,
          text: "{{footer}}",
          fontSize: 14,
          textAlign: "center",
        },
      ],
      background: "#ffffff",
    }),
  },
  {
    id: "left",
    json: JSON.stringify({
      version: "5.2.1",
      objects: [
        {
          type: "text",
          originX: "left",
          originY: "top",
          left: 60,
          top: 200,
          text: "{{title}}",
          fontSize: 48,
          fontWeight: 700,
          textAlign: "left",
        },
        {
          type: "text",
          originX: "left",
          originY: "top",
          left: 60,
          top: 260,
          text: "{{subtitle}}",
          fontSize: 24,
          textAlign: "left",
        },
        {
          type: "text",
          originX: "left",
          originY: "bottom",
          left: 60,
          top: 560,
          text: "{{footer}}",
          fontSize: 14,
          textAlign: "left",
        },
      ],
      background: "#ffffff",
    }),
  },
  {
    id: "right",
    json: JSON.stringify({
      version: "5.2.1",
      objects: [
        {
          type: "text",
          originX: "right",
          originY: "top",
          left: 740,
          top: 200,
          text: "{{title}}",
          fontSize: 48,
          fontWeight: 700,
          textAlign: "right",
        },
        {
          type: "text",
          originX: "right",
          originY: "top",
          left: 740,
          top: 260,
          text: "{{subtitle}}",
          fontSize: 24,
          textAlign: "right",
        },
        {
          type: "text",
          originX: "right",
          originY: "bottom",
          left: 740,
          top: 560,
          text: "{{footer}}",
          fontSize: 14,
          textAlign: "right",
        },
      ],
      background: "#ffffff",
    }),
  },
  {
    id: "banner",
    json: JSON.stringify({
      version: "5.2.1",
      objects: [
        {
          type: "text",
          originX: "center",
          originY: "top",
          left: 400,
          top: 160,
          text: "{{title}}",
          fontSize: 48,
          fontWeight: 700,
          textAlign: "center",
        },
        {
          type: "text",
          originX: "center",
          originY: "top",
          left: 400,
          top: 220,
          text: "{{subtitle}}",
          fontSize: 24,
          textAlign: "center",
        },
        { type: "rect", left: 0, top: 500, width: 800, height: 100, fill: "#cccccc" },
        {
          type: "text",
          originX: "center",
          originY: "center",
          left: 400,
          top: 550,
          text: "{{footer}}",
          fontSize: 16,
          textAlign: "center",
        },
      ],
      background: "#ffffff",
    }),
  },
  {
    id: "split",
    json: JSON.stringify({
      version: "5.2.1",
      objects: [
        { type: "rect", left: 0, top: 0, width: 400, height: 600, fill: "#dddddd" },
        {
          type: "text",
          originX: "left",
          originY: "top",
          left: 40,
          top: 200,
          text: "{{title}}",
          fontSize: 48,
          fontWeight: 700,
          textAlign: "left",
        },
        {
          type: "text",
          originX: "left",
          originY: "top",
          left: 40,
          top: 260,
          text: "{{subtitle}}",
          fontSize: 24,
          textAlign: "left",
        },
        {
          type: "text",
          originX: "center",
          originY: "bottom",
          left: 400,
          top: 560,
          text: "{{footer}}",
          fontSize: 14,
          textAlign: "center",
        },
      ],
      background: "#ffffff",
    }),
  },
  {
    id: "overlay",
    json: JSON.stringify({
      version: "5.2.1",
      objects: [
        { type: "rect", left: 0, top: 0, width: 800, height: 600, fill: "#000000", opacity: 0.5 },
        {
          type: "text",
          originX: "center",
          originY: "top",
          left: 400,
          top: 200,
          text: "{{title}}",
          fontSize: 48,
          fontWeight: 700,
          fill: "#ffffff",
          textAlign: "center",
        },
        {
          type: "text",
          originX: "center",
          originY: "top",
          left: 400,
          top: 260,
          text: "{{subtitle}}",
          fontSize: 24,
          fill: "#ffffff",
          textAlign: "center",
        },
        {
          type: "text",
          originX: "center",
          originY: "bottom",
          left: 400,
          top: 560,
          text: "{{footer}}",
          fontSize: 14,
          fill: "#ffffff",
          textAlign: "center",
        },
      ],
      background: "#ffffff",
    }),
  },
] as const;
